### ISSUE TITLE
.next folder instead of out folder?

### ISSUE THREAD

**Issue by andrejarboe** [netlify-templates/next-netlify-starter#3]
Hi,

I dont know if this is the right place to ask this question.

Why are you using the .next folder for deployment instead of the out folder?

Can the out folder be used on netlify for next.js 12 or is that a work in progress?

Thank you,
Andre Jarboe

**Comment by maxcell** [comment]
Howdy @andrejarboe, great question! With Next 12, the folder by default is now `.next~`, though you can set a custom directory with the `next.config.js`:

```js
module.exports = {
  distDir: 'build',
}
```

[source](https://nextjs.org/docs/api-reference/next.config.js/setting-a-custom-build-directory)
